name: Build CKAN + NetKAN

on:
  workflow_call:
    inputs:
      configuration:
        type: string
        default: Debug
    outputs:
      repack-artifact-id:
        description: "Artifact ID of the repack"
        value: ${{ jobs.build.outputs.repack-artifact-id }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      repack-artifact-id: ${{ steps.upload-repack-artifact.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache for _build/tools
        uses: actions/cache@v4
        with:
          path: _build/tools
          key: build-tools-${{ hashFiles('build', 'build.ps1', 'build.cake') }}
      - name: Restore cache for _build/cake
        uses: actions/cache@v4
        with:
          path: _build/cake
          key: build-cake-${{ hashFiles('build.cake') }}
      - name: Restore cache for _build/lib/nuget
        uses: actions/cache@v4
        with:
          path: |
            _build/lib/nuget
            ~/.nuget/packages
          key: nuget-oldref-modules-${{ hashFiles('**/packages.config') }}-${{ hashFiles('**/*.csproj') }}
      - name: Build ckan.exe and netkan.exe
        run: ./build --configuration=${{ inputs.configuration }}
      - name: Upload repack artifact
        id: upload-repack-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.configuration }}-repack-unsigned
          path: _build/repack/
          retention-days: 7
      - name: Upload out artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.configuration }}-out-unsigned
          path: _build/out/
          retention-days: 1
      - name: Upload ckan.exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: ckan.exe
          path: _build/repack/Release/ckan.exe
          retention-days: 7
        if: inputs.configuration == 'Release'
